import prisma from "../../config/prisma";
import { NotFoundError } from "../../utils/errors";
import { logger } from "../../utils/logger";
import axios from "axios";
import { analyzeComment, generateReply, validateReply } from "../ai/ai.service";
import { sendReplyToFacebook } from "../replies/reply.service";
import { evaluateRules } from "../rules/rules.service";
import type {
  GetCommentsInput,
  UpdateCommentStatusInput,
} from "./comment.validation";

export async function getComments(userId: string, filters: GetCommentsInput) {
  const { pageId, status, limit = 20, offset = 0 } = filters;

  const where: any = {
    facebookPage: {
      userId,
    },
  };

  if (pageId) {
    where.facebookPageId = pageId;
  }

  if (status) {
    where.status = status;
  }

  const [comments, total] = await Promise.all([
    prisma.comment.findMany({
      where,
      include: {
        facebookPage: {
          select: {
            pageId: true,
            pageName: true,
          },
        },
        replies: {
          orderBy: {
            createdAt: "desc",
          },
        },
      },
      orderBy: {
        createdAt: "desc",
      },
      take: limit,
      skip: offset,
    }),
    prisma.comment.count({ where }),
  ]);

  const formattedComments = comments.map((comment) => ({
    ...comment,
    facebookCommentId: comment.commentId,
    content: comment.userMessage,
    authorName: comment.userName || "Unknown",
    authorId: comment.userId,
    pageId: comment.facebookPageId,
    page: comment.facebookPage,
    reply: comment.replies?.[0]
      ? {
          ...comment.replies[0],
          content: comment.replies[0].generatedReply,
          aiConfidence: comment.replies[0].confidence,
          isAutoGenerated: true,
        }
      : undefined,
  }));

  return {
    comments: formattedComments,
    total,
    limit,
    offset,
  };
}

export async function getCommentById(userId: string, commentId: string) {
  const comment = await prisma.comment.findFirst({
    where: {
      id: commentId,
      facebookPage: {
        userId,
      },
    },
    include: {
      facebookPage: {
        select: {
          pageId: true,
          pageName: true,
        },
      },
      replies: {
        orderBy: {
          createdAt: "desc",
        },
      },
    },
  });

  if (!comment) {
    throw new NotFoundError("Comment not found");
  }

  return comment;
}

export async function updateCommentStatus(
  userId: string,
  commentId: string,
  data: UpdateCommentStatusInput,
) {
  const comment = await prisma.comment.findFirst({
    where: {
      id: commentId,
      facebookPage: {
        userId,
      },
    },
  });

  if (!comment) {
    throw new NotFoundError("Comment not found");
  }

  const updated = await prisma.comment.update({
    where: { id: commentId },
    data: {
      status: data.status,
    },
  });

  logger.info(
    { userId, commentId, status: data.status },
    "Comment status updated",
  );

  return updated;
}

export async function processComment(commentId: string) {
  const comment = await prisma.comment.findUnique({
    where: { id: commentId },
    include: {
      facebookPage: true,
    },
  });

  if (!comment) {
    throw new NotFoundError("Comment not found");
  }

  // Check if comment is already processed
  if (comment.status !== "PENDING") {
    logger.info(
      { commentId, status: comment.status },
      "Comment already processed",
    );
    return comment;
  }

  // Get AI settings for the user (or create defaults)
  let aiSettings = await prisma.aISettings.findUnique({
    where: { userId: comment.facebookPage.userId },
  });

  if (!aiSettings) {
    aiSettings = await prisma.aISettings.create({
      data: {
        userId: comment.facebookPage.userId,
        status: "ACTIVE",
        aiProvider: "openrouter",
        model: "google/gemma-4-31b-it:free",
        confidenceThreshold: 0.7,
        tone: "professional",
        language: "en",
        emojiUsage: true,
        maxLength: 500,
        spamHandling: "ignore",
        humanApprovalMode: false,
        fallbackBehavior: "skip",
      },
    });
    logger.info({ userId: comment.facebookPage.userId }, "Created default AI settings");
  }

  if (aiSettings.status !== "ACTIVE") {
    await prisma.comment.update({
      where: { id: commentId },
      data: { status: "IGNORED" },
    });
    logger.info({ commentId }, "AI not enabled, comment ignored");
    return comment;
  }

  try {
    // 1. Check custom reply rules first
    const matchingRule = await evaluateRules(
      comment.userMessage,
      comment.facebookPage.userId,
    );

    if (matchingRule) {
      logger.info(
        { commentId, ruleId: matchingRule.id, action: matchingRule.action },
        "Matching rule found for comment",
      );

      if (matchingRule.action === "IGNORE") {
        await prisma.comment.update({
          where: { id: commentId },
          data: { status: "IGNORED" },
        });
        return comment;
      }
    }

    // 2. Analyze comment with AI
    const analysis = await analyzeComment(comment.userMessage, aiSettings);

    // Update comment with AI analysis
    await prisma.comment.update({
      where: { id: commentId },
      data: {
        aiIntent: analysis.intent,
        aiSentiment: analysis.sentiment,
        aiLanguage: analysis.language,
        aiIsSpam: analysis.isSpam,
        aiConfidence: analysis.confidence,
        aiRequiresReview: analysis.requiresHumanReview,
      },
    });

    // 3. Check spam handling
    if (analysis.isSpam && aiSettings.spamHandling === "ignore") {
      await prisma.comment.update({
        where: { id: commentId },
        data: { status: "IGNORED" },
      });
      logger.info({ commentId }, "Spam detected, comment ignored");
      return comment;
    }

    // 4. Determine reply text (custom rule or AI generation)
    let replyText = "";
    let replyConfidence = analysis.confidence;
    let ruleId: string | null = null;

    if (
      matchingRule &&
      matchingRule.action === "REPLY_CUSTOM" &&
      matchingRule.customReply
    ) {
      replyText = matchingRule.customReply;
      ruleId = matchingRule.id;
      replyConfidence = 1.0;
    } else {
      // Generate reply with AI
      const replyResult = await generateReply(
        comment.userMessage,
        analysis,
        aiSettings,
      );

      // Validate reply
      const isValid = await validateReply(replyResult.reply, aiSettings);
      if (!isValid) {
        await prisma.comment.update({
          where: { id: commentId },
          data: { status: "ERROR" },
        });
        logger.error({ commentId }, "Generated reply failed validation");
        return comment;
      }

      replyText = replyResult.reply;
      replyConfidence = replyResult.confidence;
    }

    // 5. Determine if human review is required
    // When humanApprovalMode is false (auto-reply ON), the user has explicitly chosen
    // to auto-reply. Only a manually-configured HUMAN_REVIEW rule or spam-review setting
    // can override this — the AI's own requiresHumanReview flag should NOT silently
    // block auto-replies when the user has turned auto-reply ON.
    let requiresReview = false;
    if (aiSettings.humanApprovalMode) {
      // User explicitly configured "Require Human Review" in Settings — always respect this
      requiresReview = true;
    } else if (matchingRule?.action === "HUMAN_REVIEW") {
      // A configured rule explicitly triggered human review
      requiresReview = true;
    } else if (analysis.isSpam && aiSettings.spamHandling === "review") {
      // Spam handling set to review (not ignore) — queue for review
      requiresReview = true;
    }
    // NOTE: We intentionally do NOT block auto-reply based on analysis.requiresHumanReview
    // alone when humanApprovalMode is false. The user's explicit auto-reply preference wins.

    // 6. Create reply record
    const reply = await prisma.reply.create({
      data: {
        commentId: comment.id,
        facebookPageId: comment.facebookPageId,
        generatedReply: replyText,
        status: requiresReview ? "PENDING" : "APPROVED",
        aiProvider: aiSettings.aiProvider,
        ruleId,
        confidence: replyConfidence,
        requiresHumanReview: requiresReview,
      },
    });

    logger.info(
      { commentId, replyId: reply.id, requiresReview },
      "Reply created in database",
    );

    // 7. Auto-reply to Facebook if human review is NOT required
    if (!requiresReview) {
      try {
        await sendReplyToFacebook(reply.id);
        logger.info(
          { commentId, replyId: reply.id },
          "Auto-reply sent directly to Facebook!",
        );
      } catch (sendError) {
        logger.error(
          { error: sendError, commentId, replyId: reply.id },
          "Auto-reply Facebook send failed",
        );
      }
    } else {
      await prisma.comment.update({
        where: { id: commentId },
        data: { status: "PENDING" },
      });
      logger.info(
        { commentId, replyId: reply.id },
        "Reply queued for human review in dashboard",
      );
    }

    return comment;
  } catch (error) {
    logger.error({ error, commentId }, "Comment processing failed");
    await prisma.comment.update({
      where: { id: commentId },
      data: { status: "ERROR" },
    });
    throw error;
  }
}

export async function syncFacebookComments(userId: string, targetPageId?: string) {
  const where: any = {
    userId,
    isConnected: true,
  };

  if (targetPageId) {
    where.OR = [{ id: targetPageId }, { pageId: targetPageId }];
  }

  const pages = await prisma.facebookPage.findMany({ where });

  if (pages.length === 0) {
    return {
      message: "No connected Facebook pages found to sync",
      syncedCount: 0,
      newCount: 0,
      repliedCount: 0,
    };
  }

  let totalFetched = 0;
  let newCommentsCount = 0;
  let autoRepliedCount = 0;
  const errors: string[] = [];

  for (const page of pages) {
    try {
      logger.info({ pageId: page.pageId, pageName: page.pageName }, "Syncing comments from Facebook");

      const response = await axios.get(
        `https://graph.facebook.com/v18.0/${page.pageId}/feed`,
        {
          params: {
            access_token: page.pageAccessToken,
            fields: "id,message,created_time,comments{id,message,from,created_time,comments{id,message,from,created_time}}",
            limit: 25,
          },
        },
      );

      const posts = response.data?.data || [];

      for (const post of posts) {
        const comments = post.comments?.data || [];

        for (const fbComment of comments) {
          totalFetched++;
          const commentId = fbComment.id;
          const userMessage = fbComment.message;
          const from = fbComment.from;

          if (!userMessage || !commentId) continue;

          // Ignore comments made by the Page itself
          if (from && String(from.id) === String(page.pageId)) {
            continue;
          }

          // Check if comment already exists in database
          let commentRecord = await prisma.comment.findUnique({
            where: { commentId },
            include: { replies: true },
          });

          if (!commentRecord) {
            // Determine author name
            const authorName = from?.name || "Facebook User";

            commentRecord = await prisma.comment.create({
              data: {
                commentId,
                facebookPageId: page.id,
                postId: post.id,
                userId: from?.id || null,
                userName: authorName,
                userMessage,
                status: "PENDING",
                createdTime: fbComment.created_time
                  ? new Date(fbComment.created_time)
                  : new Date(),
              },
              include: { replies: true },
            });
            newCommentsCount++;
            logger.info({ commentId, postId: post.id }, "Imported comment from Facebook");
          }

          // Check if this comment already has a sent reply in our database
          const hasSentReply = commentRecord.replies?.some(
            (r) => r.status === "SENT",
          );

          // Check if Facebook already has a reply from this page to this comment (nested replies)
          const nestedReplies = fbComment.comments?.data || [];
          const pageAlreadyRepliedOnFb = nestedReplies.some(
            (sub: any) => String(sub.from?.id) === String(page.pageId),
          );

          if (hasSentReply || pageAlreadyRepliedOnFb) {
            if (commentRecord.status !== "REPLIED") {
              await prisma.comment.update({
                where: { id: commentRecord.id },
                data: { status: "REPLIED" },
              });
            }
            continue;
          }

          // If comment is PENDING or ERROR, process with AI & auto-reply
          if (
            commentRecord.status === "PENDING" ||
            commentRecord.status === "ERROR"
          ) {
            try {
              await processComment(commentRecord.id);

              const updatedReply = await prisma.reply.findFirst({
                where: { commentId: commentRecord.id, status: "SENT" },
              });

              if (updatedReply) {
                autoRepliedCount++;
              }
            } catch (procErr: any) {
              logger.warn(
                { commentId, error: procErr.message },
                "Failed to auto-process synced comment",
              );
              errors.push(`Comment ${commentId}: ${procErr.message}`);
            }
          }
        }
      }
    } catch (err: any) {
      const errMsg = err?.response?.data?.error?.message || err.message;
      logger.error(
        { pageId: page.pageId, error: errMsg },
        "Failed to sync comments for Facebook page",
      );
      errors.push(`Page ${page.pageName} (${page.pageId}): ${errMsg}`);
    }
  }

  logger.info(
    { userId, totalFetched, newCommentsCount, autoRepliedCount, errorCount: errors.length },
    "Sync Facebook comments completed",
  );

  return {
    message: `Sync completed: ${totalFetched} checked, ${newCommentsCount} imported, ${autoRepliedCount} auto-replied`,
    syncedCount: totalFetched,
    newCount: newCommentsCount,
    repliedCount: autoRepliedCount,
    errors: errors.length > 0 ? errors : undefined,
  };
}
