import prisma from "../../config/prisma";
import { NotFoundError, AuthorizationError } from "../../utils/errors";
import { logger } from "../../utils/logger";
import axios from "axios";

export async function getReplies(userId: string, filters: any) {
  const { commentId, pageId, status, limit = 20, offset = 0 } = filters;

  const where: any = {
    comment: {
      facebookPage: {
        userId,
      },
    },
  };

  if (commentId) {
    where.commentId = commentId;
  }

  if (pageId) {
    where.facebookPageId = pageId;
  }

  if (status) {
    where.status = status;
  }

  const [replies, total] = await Promise.all([
    prisma.reply.findMany({
      where,
      include: {
        comment: {
          select: {
            id: true,
            commentId: true,
            userMessage: true,
          },
        },
        facebookPage: {
          select: {
            pageId: true,
            pageName: true,
          },
        },
      },
      orderBy: {
        createdAt: "desc",
      },
      take: limit,
      skip: offset,
    }),
    prisma.reply.count({ where }),
  ]);

  const formattedReplies = replies.map((reply) => ({
    ...reply,
    content: reply.generatedReply,
    aiConfidence: reply.confidence,
    isAutoGenerated: true,
  }));

  return {
    replies: formattedReplies,
    total,
    limit,
    offset,
  };
}

export async function getReplyById(userId: string, replyId: string) {
  const reply = await prisma.reply.findFirst({
    where: {
      id: replyId,
      facebookPage: {
        userId,
      },
    },
    include: {
      comment: true,
      facebookPage: true,
    },
  });

  if (!reply) {
    throw new NotFoundError("Reply not found");
  }

  return reply;
}

export async function approveReply(userId: string, replyId: string) {
  const reply = await prisma.reply.findFirst({
    where: {
      id: replyId,
      facebookPage: {
        userId,
      },
    },
  });

  if (!reply) {
    throw new NotFoundError("Reply not found");
  }

  if (reply.status !== "PENDING") {
    throw new Error("Reply can only be approved when in PENDING status");
  }

  const updated = await prisma.reply.update({
    where: { id: replyId },
    data: {
      status: "APPROVED",
      approvedBy: userId,
    },
  });

  logger.info({ userId, replyId }, "Reply approved, sending to Facebook");

  try {
    const sent = await sendReplyToFacebook(replyId);
    return sent;
  } catch (error) {
    logger.error({ error, replyId }, "Failed to send approved reply to Facebook");
    return updated;
  }
}

export async function rejectReply(userId: string, replyId: string) {
  const reply = await prisma.reply.findFirst({
    where: {
      id: replyId,
      facebookPage: {
        userId,
      },
    },
  });

  if (!reply) {
    throw new NotFoundError("Reply not found");
  }

  if (reply.status !== "PENDING") {
    throw new Error("Reply can only be rejected when in PENDING status");
  }

  const updated = await prisma.reply.update({
    where: { id: replyId },
    data: {
      status: "SKIPPED",
    },
  });

  logger.info({ userId, replyId }, "Reply rejected");

  return updated;
}

export async function retryReply(userId: string, replyId: string) {
  const reply = await prisma.reply.findFirst({
    where: {
      id: replyId,
      facebookPage: {
        userId,
      },
    },
    include: {
      comment: true,
      facebookPage: true,
    },
  });

  if (!reply) {
    throw new NotFoundError("Reply not found");
  }

  if (reply.status !== "FAILED") {
    throw new Error("Reply can only be retried when in FAILED status");
  }

  // Update status to PENDING for retry
  await prisma.reply.update({
    where: { id: replyId },
    data: {
      status: "PENDING",
      errorMessage: null,
    },
  });

  logger.info({ userId, replyId }, "Reply marked for retry, sending to Facebook");

  try {
    const sent = await sendReplyToFacebook(replyId);
    return sent;
  } catch (error) {
    logger.error({ error, replyId }, "Failed to retry send reply to Facebook");
    throw error;
  }
}

export async function sendReplyToFacebook(replyId: string) {
  const reply = await prisma.reply.findUnique({
    where: { id: replyId },
    include: {
      comment: true,
      facebookPage: true,
    },
  });

  if (!reply) {
    throw new NotFoundError("Reply not found");
  }

  if (!reply.facebookPage.isConnected) {
    throw new Error("Facebook page is not connected");
  }

  try {
    // Send reply to Facebook Graph API as form-urlencoded for maximum compatibility
    const params = new URLSearchParams();
    params.append("message", reply.generatedReply);
    params.append("access_token", reply.facebookPage.pageAccessToken);

    const response = await axios.post(
      `https://graph.facebook.com/v18.0/${reply.comment.commentId}/comments`,
      params.toString(),
      {
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
        },
      },
    );

    if (response.data && response.data.id) {
      // Update reply with Facebook reply ID
      const updated = await prisma.reply.update({
        where: { id: replyId },
        data: {
          replyId: response.data.id,
          status: "SENT",
        },
      });

      // Update comment status
      await prisma.comment.update({
        where: { id: reply.commentId },
        data: { status: "REPLIED" },
      });

      logger.info(
        { replyId, facebookReplyId: response.data.id },
        "Reply sent to Facebook successfully",
      );

      return updated;
    } else {
      throw new Error("Failed to send reply to Facebook (no ID returned)");
    }
  } catch (error: any) {
    const fbError = error?.response?.data?.error;
    const errorDetails = fbError
      ? `Meta Graph API error: ${fbError.message} (Code: ${fbError.code}, Subcode: ${fbError.error_subcode || "none"})`
      : error instanceof Error
        ? error.message
        : "Unknown error";

    logger.error(
      {
        error: fbError || error?.response?.data || error?.message,
        replyId,
        commentId: reply.comment.commentId,
      },
      "Failed to send reply to Facebook",
    );

    // Update reply status to FAILED
    await prisma.reply.update({
      where: { id: replyId },
      data: {
        status: "FAILED",
        errorMessage: errorDetails,
      },
    });

    throw error;
  }
}
